apiVersion: v1
kind: Service
metadata:
  name: simple-webserver-service
spec:
  selector:
    app: simple-webserver
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
